### PR TITLE
Improve API clarity

### PR DESCRIPTION
**Pull request by pakdev**
Renamed properties so they don't sound like actions, renamed methods so they
sound like actions, and converted callback properties to methods to enable
proper overloading.

### CODE REVIEW

**Comment by elect86** [comment]
Hi Peter,

Thanks for your pull, much appreciated, I wanted to revise that code since a while too.. 

Let's say I agree on everything except:

- I wouldn't like to give up on `aspect`: I recognize it makes sense to have `aspectRatio` to match `glfwSetWindowAspectRatio` and have it as a `Vec2` variable. 
But I also like the possibility to retrieve directly the result of the division like [here](https://github.com/java-opengl-labs/learn-OpenGL/blob/master/src/main/kotlin/learnOpenGL/a_gettingStarted/6.1%20coordinate%20systems.kt#L179):
`val projection = glm.perspective(45f.rad, window.aspect, 0.1f, 100f)`
One thing that is tricky is that it'd be more logic to exchange the names, that is `aspect: Vec2i` and `aspectRatio: Float`, but then we won't be coherent anymore with glfw..
that's why I came up with that solution at that time, can we come to a common point that satisfies both?

- I also wouldn't like to give up on the callback variables, I love being able to simply write:
`framebufferSizeCallback = { size -> glViewport(size) }`
I find it clearer compared to 
`setFramebufferSizeCallback{ size -> glViewport(size) }`
Even more if we talk about function references
`cursorPosCallback = ::mouseCallback`
vs
`setCursorPosCallback(::mouseCallback)`
but I do see your point here and I agree, `framebufferSizeCallBack` vs `framebufferSizeCallback` smells bad..
therefore what about having both ways, that is a method for the dead plain version:
`fun setFramebufferSizeCallback(callbackFunc: (Int, Int) -> Unit)`
and a variable with custom set for the concise one?
`var framebufferSizeCallback: ((Vec2i) -> Unit)? = null`
I'm totally inclined to trade some redundancy in uno to have the possibility to have a concise way outside the library..

In the meanwhile we sort out these points, I'm gonna to accept your changes and then modify it accordingly to what I wrote..

I'm used to do frequent vertical (from lower to higher level lib) updates, so changes can be taken into account quite fast

Nice catch on the `Monitor` with the default parameter!

Ps: I'm gonna remove just the uselss `!!` from your callback methods and use directly the `()` operator

**Comment by elect86** [comment]
[Done](https://github.com/kotlin-graphics/uno-sdk/commit/3b45b78a50c4a9a7a3beb01aee4130ec9794ff38)

Looking forward for feedbacks :)

Ps: I'd be glad to have you on board

**Comment by pakdev** [comment]
Thanks for being responsive, thoughtful, and willing to pull!

1. What if we kept `aspectRatio` as-is and added the read-only property `val aspect = size.x / size.y`? This makes sense to me since a "ratio" consists of two numbers.

2. How often do you use the destructured version e.g. `(Int, Int) -> Unit` of the callback? I searched for "callback" in [this repository](https://github.com/java-opengl-labs/learn-OpenGL/search?utf8=%E2%9C%93&q=callback&type=) and only ever saw the Vec2d/Vec2i version being used. Since you prefer conciseness and I prefer consistency, perhaps we can meet in the middle by only supporting `var ___Callback = (Vec2x) -> Unit`?

I laud your approach to software development, and good catch about the `!!.invoke`.

**Comment by elect86** [comment]
Yep, no problem

1) yeah, why not. I still didnt happen to set `aspect: Float` yet, I can make it `val` and comment the `setter` for future convenience

2) So far never if I recall properly.. but I did that because I thought there are people wanting to use it.. 
anyway, we can totally do as you suggest and if someone complains or offer a better solution, we'll discuss it again

Thanks, appreciated :)

**Comment by elect86** [comment]
Something like [this](https://github.com/kotlin-graphics/uno-sdk/commit/49a44ad0355c7bbc3e076bf282133a7949bc226b)?

**Comment by pakdev** [comment]
Yeah - made minor comments

**Comment by elect86** [comment]
Replied :)

However, talking about listeners, in these last days I recently met kind of an issue in [imgui](https://github.com/kotlin-graphics/imgui) (also [here](https://github.com/kotlin-graphics/imgui/issues/14))

That is, I cannot add multiple callback of the same time because of course at the moment we support only one and that'd be always replaced..

This, of course, can be handled at higher level, but it'd be nice if it was implemented out-of-the-box..

What I am thinking of, is something similar to what jogl does with their newt window, that is having multiple listeners for each type.

We could have a mutable map `<String, callback: (x) -> Unit>` for each callback type, where we add all the callback of the given type with a short description (so that you can always look into that and have an hint about what that callback is for)

What's your feedback about?

**Comment by elect86** [comment]
I created a new branch and [pushed](https://github.com/kotlin-graphics/uno-sdk/commit/db0a23649e1f394fb6858ccad5f33ee4c79888f9)

**Comment by pakdev** [comment]
Why would we want to allow the registration of multiple callbacks? That doesn't seem to be supported by glfw

**Comment by elect86** [comment]
To avoid making it manually.

In the example above, imgui has its own callbacks and the applications I'm importing imgui into, does have it as well.

So instead having to create a single big callback and there manually call the real application callback + the imgui one, I can simply pass both and they will both executed in loop whenever glwf callbacks..

I also opened an [issue](https://github.com/glfw/glfw/issues/1185) over there

**Comment by pakdev** [comment]
Ahh, I see the benefit.

How does the changes in your branch allow multiple callbacks to be set? Wouldn't only one callback ("0 - Default") only ever get set/cleared (if clients use the properties)?

**Comment by elect86** [comment]
Well, at the begin I thought if one wants to get hands on that he shall use directly [`window.cb.framebufferSize.map`](https://github.com/kotlin-graphics/uno-sdk/blob/multipleCallbacks/src/main/kotlin/uno/glfw/GlfwWindow.kt#L156), but we could polish it a little and provide a better way to do it..

I don't know, `addFramebufferSizeCallback` or `addFramebufferSizeCallbackAlong`? 

I added the `0` at the begin in order to also offer the user the possibility to control the order of execution, if you pass `1 - ImGui` you know it will be executed after the default one, whatever it is

Maybe we could explicit that via a requested parameter in the method: `addFramebufferSizeCallback(index: Int, callback)`? 

And then, of course, the corresponding version `remove*`

**Pull request merged**
